.\"Copyright 2010-2011 (c) EPFL
.TH DTK_CREATE_SHAPE 3 2011 "EPFL" "Draw Toolkit manual"
.SH NAME
dtk_create_shape - Create and modify custom shape
.SH SYNOPSIS
.LP
.B #include <drawtk.h>
.sp
.BI "dtk_hshape dtk_create_shape(dtk_hshape " shp ","
.br
.BI "                unsigned int " ind_num ", const float *" vertex_array ","
.br
.BI "                int " filled ", const float *" color ");"
.br
.SH DESCRIPTION
.LP
\fBdtk_create_shape\fP() creates a shape specified by \fIind_num\fP vertices
referenced by \fIvertex_array\fP. In this array, the position parameters (x,y)
of each vertex are packed together and the list should ordered, so that the
array is filled in the following way: x0,y0,x1,y1,x2,y2,...,xN,yN.
.LP
\fIshp\fP, \fIfilled\fP and \fIcolor\fP have the same usage and meaning as for
other shape creation function:
.IP " *" 3
\fIshp\fP can be used to modify a previously created shape. If it is non-null,
the handle will be used to modify the shape referenced by \fIshp\fP: no new
shape is created and the returned value is ensured to be \fIshp\fP in case of
success, \fINULL\fP otherwise. If \fIshp\fP is \fINULL\fP, the function will
attempt to create a new shape.
.LP
.IP " *" 3
\fIfilled\fP is set to 0 if the described shape should be a continuous line or a
non-null value if the shape is supposed to be filled polygon. In the case of
filled polygon request, the last point specified in \fIvertex_array\fP will be
connected with the first one.
.LP
.IP " *" 3
\fIcolor\fP should point to a 4 float array containing a normalized RGBA value
(i.e. each component is between 0.0 and 1.0).
.SH "RETURN VALUE"
.LP
In case of success these functions return the handle to the newly created or modified
shape. If the \fIshp\fP argument is non-null, the handle returned is the
same value. In case of error, \fINULL\fP is returned.
.SH "SEE ALSO"
.BR dtk_destroy_shape (3)


