.\"Copyright 2011 (c) EPFL
.TH DTK_VIDEO_EXEC 3 2011 "EPFL" "Draw Toolkit manual"
.SH NAME
dtk_video_exec - Start/stop/pause a video texture
.SH SYNOPSIS
.LP
.B #include <dtk_video.h>
.sp
.BI "int dtk_video_exec(dtk_htex " vid ", int " command ");"
.br
.SH DESCRIPTION
.LP
This function changes the state of a video texture referenced by \fIvid\fP
according to the value of \fIcommand\fP: \fBDTKV_CMD_PLAY\fP,
\fBDTKV_CMD_PAUSED\fP, \fBDTKV_CMD_STOP\fP. \fIvid\fP must be a dynamic
texture created by one of the functions \fBdtk_create_video_*\fP(3). If the
video was already in the requested state, the function will do nothing.
.SH "RETURN VALUE"
.LP
0 if the state has been changed or was already the one requested, -1 otherwise.
.SH "SEE ALSO"
.BR dtk_load_video_file (3),
.BR dtk_load_video_gst (3),
.BR dtk_load_video_test (3),
.BR dtk_load_video_udp (3),
.BR dtk_load_video_tcp (3)


