.\"Copyright 2011 (c) EPFL
.TH DTK_ADDTIME 3 2011 "EPFL" "Draw Toolkit manual"
.SH NAME
dtk_addtime - timestamp adjustment function
.SH SYNOPSIS
.LP
.B #include <dtk_time.h>
.sp
.BI "int dtk_addtime(struct dtk_timespec* " ts ", long " sec ", long " nsec ");"
.br
.SH DESCRIPTION
The function \fBdtk_addtime\fP() adjusts the time pointed by \fIts\fP by 
adding \fIsec\fP seconds and \fInsec\fP nanoseconds. 
.SH "RETURN VALUE"
.LP
On success, the function returns 0, otherwise -1.
.SH ERRORS
.LP
\fBdtk_addtime\fP() will fail if:
.TP
.B EINVAL
The value in the \fInsec\fP field was not in the range -999999999 to
999999999.
.SH "SEE ALSO"
.BR dtk_nanosleep (3),
.BR dtk_gettime (3)

