.\"Copyright 2010 (c) EPFL
.TH DTK_DRAW_SHAPE 3 2010 "EPFL" "Draw Toolkit manual"
.SH NAME
dtk_destroy_shape - Destroy a shape
.SH SYNOPSIS
.LP
.B #include <drawtk.h>
.sp
.BI "void dtk_destroy_shape(const dtk_hshape " shp ");"
.br
.SH DESCRIPTION
.LP
\fBdtk_destroy_shape\fP() destroys the shape referenced by \fIshp\fP. If \fIshp\fP is \fINULL\fP the function returns without doing anything.
.SH "RETURN VALUE"
.LP
None.
.SH "SEE ALSO"
.BR dtk_create_shape (3)

